name: Rescue Token
on: [workflow_dispatch]
jobs:
  rescue:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          ENGINE: ${{ secrets.G_DRIVE_TOKEN_ENGINE }}
          DATA: ${{ secrets.G_DRIVE_TOKEN }}
        run: |
          echo "ENGINE_START"
          echo "$ENGINE" | base64
          echo "ENGINE_END"
          echo "DATA_START"
          echo "$DATA" | base64
          echo "DATA_END"
